# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setting up MSBuild
        uses: microsoft/setup-msbuild@v1.1
        
      #- name: Setting up NuGET
        # You may pin to the exact commit or the version.
        # uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1
        #uses: NuGet/setup-nuget@v1.0.5

      # Runs a set of commands using the runners shell
      #- name: Restore NuGET Packages
      #  run: nuget restore "\winformsapp\Nova Folder Creator GUI\Nova Folder Creator GUI.sln"
        
      # Build x86
      - name: Building the software
        run:
          cd "\winformsapp\Nova Folder Creator GUI\"
          dotnet publish -r win7-x86 -sc
